# This workflow will pull docker images from gcr.io quay.io and push it to dockerhub or aliyun registry.
#
# To configure this workflow:
#
# 1. Set up env-->global variables as your own: 
#
# 2. Change the values for the DOCKERHUB_PASSWORDã€ALI_PASSWORD environment variables in travis-ci.com:
#    choose "more options-->settings-->Environment Variables"

os: linux
dist: bionic
language: shell
services: docker

env:
  global:
    - DOCKERHUB_USERNAME=edwin1987

before_script:
  # - echo "$DOCKERHUB_PASSWORD" | docker login -u "$DOCKERHUB_USERNAME" --password-stdin
  - docker logout
  - docker login -u "$DOCKERHUB_USERNAME" -p "$DOCKERHUB_PASSWORD"
 
script:
  - |
    echo "start pull retag and push"
    version=v1.18.10
    count=$(cat images-$version.txt | wc -l)
    icount=1
    for image in `cat images-$version.txt`
    do
      echo [$icount/$count]: $image
      # image_name=${image##*/}
      docker pull $image
      docker tag $image $DOCKERHUB_USERNAME/$image
      
      # push to dockerhub
      docker push $DOCKERHUB_USERNAME/$image
      ((icount++))
    done

after_script:
  - docker images --format "{{.Repository}}:{{.Tag}}" | grep $DOCKERHUB_USERNAME
